media:
  input: uploads
  output: /uploads
content:
  - name: drafts
    label: Drafts
    path: _drafts
    type: collection
  - name: pages
    label: Pages
    path: pages
    type: collection
    view:
      fields: [ title, published ]
      sort: [ nav_order ]
      order: asc
    fields:
      - name: title
        label: Title
        type: string
      - name: nav_order
        label: Navigation order
        type: number
      - name: body
        label: Body
        type: rich-text
      - name: permalink
        label: Permalink
        type: string
      - name: splash
        label: Splash
        type: image
      - name: layout
        label: Layout
        type: select
        options:
          values: [ page, post ]
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view:
      fields: [ title, published, date ]
      sort: [ date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: categories
        label: Categories
        type: string
        list: true
      - name: excerpt
        label: Excerpt
        type: rich-text
      - name: splash_image
        label: Splash Image
        type: image